// <auto-generated />
namespace Fisabrantes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removerasituacaoprofissional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removerasituacaoprofissional));
        
        string IMigrationMetadata.Id
        {
            get { return "201809251718371_remover a situacao profissional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
